# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'AndroidTimeMachine'
tagline:             'A Graph-based Dataset of Commit History of Real-World Android apps'
description:         'AndroidTimeMachine — A Graph-based Dataset of Commit History of Real-World Android apps'
url:                 https://androidtimemachine.github.io
baseurl:             ''

# About/contact
author:
  name:              Franz-Xaver Geiger
  email:             f.geiger@student.vu.nl

# Custom vars
version:             1.0.0
